# Generated by Django 3.2 on 2025-06-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('VW', 'Volkswagen'), ('FI', 'Fiat'), ('FO', 'Ford'), ('GM', 'Chevrolet'), ('HY', 'Hyundai'), ('TO', 'Toyota'), ('HO', 'Honda'), ('NI', 'Nissan'), ('BM', 'BMW'), ('MB', 'Mercedes-Benz')], max_length=2)),
                ('modelo', models.CharField(max_length=50)),
                ('ano_fabricacao', models.PositiveIntegerField()),
                ('ano_modelo', models.PositiveIntegerField()),
                ('motorizacao', models.DecimalField(decimal_places=1, max_digits=2)),
                ('combustivel', models.CharField(choices=[('G', 'Gasolina'), ('A', 'Álcool'), ('D', 'Diesel'), ('F', 'Flex'), ('E', 'Elétrico'), ('H', 'Híbrido')], max_length=1)),
                ('cor', models.CharField(max_length=30)),
                ('quilometragem', models.PositiveIntegerField()),
                ('numero_portas', models.PositiveIntegerField(choices=[(2, '2 portas'), (4, '4 portas')])),
                ('transmissao', models.CharField(choices=[('A', 'Automática'), ('M', 'Manual'), ('S', 'Semi-automática')], max_length=1)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
